### PR TITLE
Possibility to set clipboard command

### PR DESCRIPTION
**Pull request by dyuri**
Since I both have `xclip` and `wl-copy` installed and I don't want to uninstall `xclip`, I wanted to be able to manually set the clipboard copy command.

You can now set it via:
- command line flag `-c`
- configuration option `clipboard_cmd`

If not set, it falls back to the old autodetect mechanism.

### CODE REVIEW

**Comment by tjblackheart** [comment]
Hi @dyuri, thank you very much! I love that idea, however this implementation will crash if somebody enters a random string as clipboard_cmd into the config (i.e. a nonexistent binary). 

I suppose the easiest way to fix that would be to just add the (basepathed) custom string into the `cmds` slice, then the  `exec.LookPath` check can work in any case.

**Comment by dyuri** [comment]
👍
My problem with that is, that I also want to use some command line arguments (currently `wl-copy -p -n`), but I'll try to come up with something.

**Comment by dyuri** [comment]
What about this kind of messaging?
image

**Comment by tjblackheart** [comment]
Hello @dyuri! I am very very sorry for the very late reply - for the last year I was living abroad without access to a computer or the internet. But now I am back, and I'll take a look at this as soon as possible. Thanks!

**Comment by dyuri** [comment]
No worries, I'm glad you're OK. 👍

**Comment by tjblackheart** [comment]
Thanks, merged.

**Pull request merged**
