### PR TITLE
Add support for 2FAS

### PR DESCRIPTION
**Pull request by elliotwutingfeng**
### Changes

- Add support for opening [2FAS](https://2fas.com) encrypted vaults.

### CODE REVIEW

**Comment by tjblackheart** [comment]
Hello @elliotwutingfeng! I am very very sorry for the very late reply - for the last year I was living abroad without access to a computer or the internet. But now I am back, and I'll take a look at this as soon as possible. Thanks in advance for all this work here!

**Comment by elliotwutingfeng** [comment]
Cool. I thought you went off the grid. Don't worry about it.

**Comment by tjblackheart** [comment]
Hey @elliotwutingfeng, could you update your PRs with the latest main? Thanks

**Comment by tjblackheart** [comment]
Thank you, merged.

**Pull request merged**
